import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { AuthProvider } from "@/components/auth/AuthProvider";
import { getAuthenticatedAppForUser } from "@/lib/firebase/serverApp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { currentUser } = await getAuthenticatedAppForUser();
  // Stringify and parse to prevent infinite stringification
  const initialUser = JSON.parse(JSON.stringify(currentUser));

  return (
    <html lang="en" className="h-full">
      <body
        className={`h-full flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex-1">
          <AuthProvider initialUser={initialUser}>{children}</AuthProvider>
        </div>
        <footer className="flex-none">
          <a
            target="_blank"
            rel="nooper noreferrer"
            href="https://github.com/matthova/nextjs-firebase-server-cookies"
          >
            Check out the code on Github
          </a>
        </footer>
      </body>
    </html>
  );
}
